name: TikTok downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'TikTok URL to grab'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -U yt-dlp
      - run: python main.py
        env:
          TIKTOK_URL: ${{ github.event.inputs.url }}

      - uses: actions/upload-artifact@v4
        with:
          name: tiktok-video
          path: '*.mp4'
